parameters:
    dirisi.website.film.manager.class: Dirisi\WebsiteBundle\Manager\FilmManager
    dirisi.website.film.form.handler.class: Dirisi\WebsiteBundle\Form\Film\Handler\FilmFormHandler
    dirisi.website.film.form.type.class: Dirisi\WebsiteBundle\Form\Film\Type\FilmType

services:
    #               
    # manager Configuration
    #      
    dirisi.process.manager.film:
        class: %dirisi.website.film.manager.class%
        arguments:  ["@translator", "@doctrine.orm.entity_manager", "@service_container"]   
        
    #               
    # form type Configuration
    #  
    dirisi.website.film.form.type:
        class: %dirisi.website.film.form.type.class%
        tags:
            - { name: form.type , alias: dirisi_website_film } 
            
    #               
    # form handler default Configuration
    #          
    dirisi.website.film.form.factory:
        class: Symfony\Component\Form\Form
        factory_method: create
        factory_service: form.factory
        arguments:        
            - @dirisi.website.film.form.type
            - ~
            - { category_hidden: false } 
            
    dirisi.website.film.form.handler:
        class: %dirisi.website.film.form.handler.class%
        scope: request
        arguments: ["@dirisi.website.film.form.factory", "@dirisi.process.manager.film", "@request"]
        
    #               
    # form handler simple Configuration
    #       
    dirisi.website.film.form.factory.simple:
        class: Symfony\Component\Form\Form
        factory_method: create
        factory_service: form.factory
        arguments:        
            - @dirisi.website.film.form.type
            - ~
            - { category_hidden: true }            
            
    dirisi.website.film.form.handler.simple:
        class: %dirisi.website.film.form.handler.class%
        scope: request
        arguments: ["@dirisi.website.film.form.factory.simple", "@dirisi.process.manager.film", "@request"]   
        
        
        
        
      
        
        
        
       