services:
    security_authentication_success_handler:
        class:  Dirisi\AuthBundle\Handler\AuthenticationSuccessHandler
        arguments:  ["@router", "@security.context", "@security.http_utils", {}]
        tags:
            - { name: 'monolog.logger', channel: 'security' }

    security_authentication_failure_handler:
        class:  Dirisi\AuthBundle\Handler\AuthenticationFailureHandler
        arguments:  ["@http_kernel", "@security.http_utils", {}, "@logger"]
        tags:
            - { name: 'monolog.logger', channel: 'security' }
            
    security_logout_success_handler:
        class:  Dirisi\AuthBundle\Handler\LogoutSuccessHandler
        arguments:  ["@router", "@doctrine.orm.entity_manager"]
        tags:
            - { name: 'monolog.logger', channel: 'security' }            