parameters:
    dirisi.website.film.handler.class: Dirisi\WebsiteBundle\Handler\FilmHandlerProcess
    dirisi.website.film.form.handler.class: Dirisi\WebsiteBundle\Form\Film\Handler\FilmFormHandler
    dirisi.website.film.form.type.class: Dirisi\WebsiteBundle\Form\Film\Type\FilmType

services:
    dirisi.process.handler.film:
        class: %dirisi.website.film.handler.class%
        arguments:  ["@translator", "@doctrine.orm.entity_manager", "@service_container"]    
        
    dirisi.website.film.form:
        class: Symfony\Component\Form\Form
        arguments: ["@dirisi.website.film.form.type"]
        factory_method: create
        factory_service: form.factory

    dirisi.website.film.form.type:
        class: %dirisi.website.film.form.type.class%
        tags:
            - { name: form.type , alias: dirisi_website_film }

    dirisi.website.film.form.handler:
        class: %dirisi.website.film.form.handler.class%
        scope: request
        arguments: ["@dirisi.website.film.form", "@dirisi.process.handler.film", "@request"]