parameters:
    dirisi.handler.exception.class: Dirisi\WebsiteBundle\EventListener\HandlerException
    dirisi.handler.localeHandler.class: Dirisi\WebsiteBundle\EventListener\HandlerLocale
    dirisi.event_subscriber.acteur.class: Dirisi\WebsiteBundle\EventSubscriber\EventSubscriberActeurBundle
    dirisi.twig.extension.tool.class: Dirisi\WebsiteBundle\Twig\Extension\PiToolExtension

services:       
    #
    # configuration of the twig extensions
    #               
    twig.extension.tool:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }
           
    #
    # configuration of the sfynx extensions
    #         
    dirisi.tool.twig.extension.tool:
        class: %dirisi.twig.extension.tool.class%
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }           
           
    #               
    # handlers Configuration
    #           
    dirisi.exception_handler:
        class: %dirisi.handler.exception.class%
        arguments: [@templating, @kernel, @service_container]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException } 
            
    dirisi.locale_handler:
        class: %dirisi.handler.localeHandler.class%
        arguments: [%locale%, @service_container]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 66 }
            
            
    #
    # configuration of the event subscriber of entities
    #
    dirisi.event_subscriber.acteur:
        class: %dirisi.event_subscriber.acteur.class%
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_subscriber }             
            