<?php

namespace Dirisi\WebsiteBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilmRepository extends \Doctrine\ORM\EntityRepository
{
    public function saveByMerge($entity) 
    {
        $this->_em->merge($entity); # not forget to add merge cascade to the manytpmany relationship in film entity
        $this->_em->flush();
    }
    
    public function allOrderByTitle($max)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('f')
          ->from($this->_entityName, 'f')
          ->orderBy('f.titre', 'ASC')
          ->setMaxResults($max);        
        $query = $qb->getQuery();
        
        return $query->getResult();
    }
    
    public function remove($entity)
    {
        $this->_em->remove($entity);
        $this->_em->flush(); 
    }
}
