
            # Liste des pages accessibles à tous les utilisateurs (ne pas toucher)
            - { path: ^/_wdt/, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/_profiler/, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/js/, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/css/, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/resseting$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            # PAGES ACCESSIBLES AUX ADMINISTRATEURS
            - { path: ^/myapp/admin/, role: ROLE_ADMIN }
            # PAGES ACCESSIBLES AUX UTILISATEURS CONNECTES
            - { path: ^/myapp/change-password, role: ROLE_USER }
            # PAGES ACCESSIBLES À TOUS
            - { path: ^/myapp.*, role: IS_AUTHENTICATED_ANONYMOUSLY }

