#!/bin/sh

PLATEFORM_PROJET_NAME_LOWER=$(echo $PLATEFORM_PROJET_NAME | awk '{print tolower($0)}') # we lower the string
PLATEFORM_PROJET_NAME_UPPER=$(echo $PLATEFORM_PROJET_NAME | awk '{print toupper($0)}') # we lower the string
DATABASE_NAME="${PLATEFORM_INSTALL_NAME}_${PLATEFORM_PROJET_NAME_LOWER}"
DATABASE_NAME_TEST="${PLATEFORM_INSTALL_NAME}_${PLATEFORM_PROJET_NAME_LOWER}_test"