
# jms_security_extra Configuration
# http://jmsyst.com/bundles/JMSSecurityExtraBundle/master/configuration
jms_security_extra:
    # Whether you want to secure all services (true), or only secure specific
    # services (false); see also below
    secure_all_services: false # important for optimal perform
    
    # Enables expression language
    expressions: true
    
    # Allows you to specify access control rules for specific methods, such
    # as controller actions
    method_access_control: { }
    
# jms_di_extra Configuration
# http://jmsyst.com/bundles/JMSDiExtraBundle/master/configuration
jms_di_extra:
    locations:
        all_bundles: true
        directories: ["%kernel.root_dir%/../src"] # important for optimal perform
    automatic_controller_injections:
        properties:
            request: "@request"
            router: "@router"
        method_calls:
            setRouter: ["@router"] 

            