<?php

namespace Dirisi\WebsiteBundle\Entity\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilmRepository extends \Doctrine\ORM\EntityRepository
{
    public function save($entity) {
        $this->_em->persist($entity);
        $this->_em->flush();
    }
}
