myapp_accueil:
  path: /
  defaults: { _controller: MyAppSiteBundle:Default:index }
myapp_acteur_lister:
  path: /acteur/
  defaults: { _controller: MyAppSiteBundle:Acteur:lister }
myapp_acteur_ajouter:
  path: /admin/acteur/ajouter
  defaults: { _controller: MyAppSiteBundle:Acteur:editer }
myapp_acteur_modifier:
  path: /admin/acteur/modifier/{id}
  defaults: { _controller: MyAppSiteBundle:Acteur:editer }
myapp_acteur_supprimer:
  path: /admin/acteur/supprimer/{id}
  defaults: { _controller: MyAppSiteBundle:Acteur:supprimer }
myapp_acteur_rechercher:
  path: /acteur/rechercher
  defaults: { _controller: MyAppSiteBundle:Acteur:rechercher }
  requirements:
    _method: POST
myapp_film_lister:
  path: /film/
  defaults: { _controller: MyAppSiteBundle:Film:lister }
myapp_film_ajouter:
  path: /admin/film/ajouter
  defaults: { _controller: MyAppSiteBundle:Film:editer }
myapp_film_modifier:
  path: /admin/film/modifier/{id}
  defaults: { _controller: MyAppSiteBundle:Film:editer }
myapp_film_supprimer:
  path: /admin/film/supprimer/{id}
  defaults: { _controller: MyAppSiteBundle:Film:supprimer }
myapp_film_voir:
  path: /film/voir/{id}
  defaults: { _controller: MyAppSiteBundle:Film:voir }
myapp_choisir_langue:
  path: /choisir-langue/{langue}
  defaults: { _controller: MyAppSiteBundle:Default:choisirLangue } 