
doctrine:
    dbal:
        connections:
            default:
                driver:   %test_database_driver%
                host:     %test_database_host%
                port:     %test_database_port%
                dbname:   %test_database_name%
                user:     %test_database_user%
                password: %test_database_password%
                