    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     "%%database.name.env.myproject%%"
    database_user:     "%%database.user.env.myproject%%"
    database_password: "%%database.password.env.myproject%%"

    test_database_driver:   pdo_mysql
    test_database_host:     localhost
    test_database_port:     ~
    test_database_name:     "%test.database.name.env.myproject%"
    test_database_user:     "%test.database.user.env.myproject%"
    test_database_password: "%test.database.password.env.myproject%"    

