dirisi_test:
    resource: "@DirisiTestBundle/Controller/"
    type:     annotation
    prefix:   /dirisi

dirisi_website:
    resource: "@DirisiWebsiteBundle/Controller/"
    type:     annotation
    prefix:   /

dirisi_auth:
    resource: "@DirisiAuthBundle/Controller/"
    type:     annotation
    prefix:   /


#
#   Import FOSUserBundle routing files
#
fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /dirisi/admin/fosgroup    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /dirisi
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /dirisi/profile
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /dirisi/register
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /dirisi/resetting
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /dirisi/change-password

#
#   Import DirisiWebsiteBundle routing files
#
dirisi_site_bundle:
    resource: "@DirisiWebsiteBundle/Resources/config/routing.yml"
    prefix: /dirisi
    
